In [1]:
import numpy as np
from glob import glob
D = 0.9

In [2]:
graph_paths = glob("Project3 Dataset/graph_*.txt")
graphs = []
for graph_path in graph_paths:
    with open(graph_path , "r") as f:
        edges = []
        edge = f.readline()
        while edge:
            v1 , v2 = edge.split(",")
            v1,v2 = int(v1), int(v2)
            edges.append([v1,v2])
            edge = f.readline()
        m = np.amax(edges)
    adj_matrix = np.zeros([m,m])
    for edge in edges:
        v1,v2 = edge
        adj_matrix[v1-1][v2-1] = 1
    
    graphs.append(adj_matrix)

In [3]:
Bs = []
for graph in graphs:
    B = np.array(np.zeros([len(graph),len(graph)]))
    count = 0
    for r in graph:
        oD = np.sum(r)
        if oD != 0:
            rp_row = graph[count]/oD
        B[count] = rp_row
        count += 1
    #print(B)
    Bs.append(B.T)

In [4]:
Rps = []
for B in Bs:
    Rp = np.ones([len(B),1]) / len(B)
    Rp = (B @ Rp) * D + (1-D)
    newRp = (B @ Rp) * D + (1-D)
    diff =  Rp - newRp
    while diff.any()> 0.01:
         Rp = newRp
         newRp = (B @ Rp) * D + (1-D)
         diff = Rp - newRp
    Rp = Rp / np.linalg.norm(Rp)
    Rp = Rp / np.sum(Rp)
    Rps.append(Rp)


In [5]:
for Rp in Rps:
    print(Rp)

[[0.01666667]
 [0.03166667]
 [0.04516667]
 [0.05731667]
 [0.06825167]
 [0.78093167]]
[[0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]]
[[0.17241379]
 [0.32758621]
 [0.32758621]
 [0.17241379]]
[[0.2880119 ]
 [0.16104085]
 [0.13942021]
 [0.10724631]
 [0.1827487 ]
 [0.05540417]
 [0.06612786]]
[[0.00021322]
 [0.00021322]
 [0.00021322]
 [0.00021322]
 [0.00021322]
 [0.0002452 ]
 [0.00023241]
 [0.00024063]
 [0.00026119]
 [0.00026119]
 [0.00024063]
 [0.00023241]
 [0.00026119]
 [0.00026119]
 [0.00023241]
 [0.00034469]
 [0.00034218]
 [0.00295992]
 [0.00039581]
 [0.0007786 ]
 [0.01018267]
 [0.00972678]
 [0.0007786 ]
 [0.01429018]
 [0.00235464]
 [0.00024475]
 [0.0002488 ]
 [0.00034218]
 [0.00034218]
 [0.00407563]
 [0.00150305]
 [0.0002854 ]
 [0.00308778]
 [0.00030691]
 [0.00755292]
 [0.00055122]
 [0.00098048]
 [0.00026007]
 [0.0007786 ]
 [0.00469918]
 [0.00034218]
 [0.0007786 ]
 [0.01282768]
 [0.01851473]
 [0.00034218]
 [0.00482667]
 [0.00254763]
 [0.00035993]
 [0.00034469]
 [0.00033322]
 [0.00034469]
 [0.00028