In [10]:
import numpy as np

In [13]:
with open("Project3 Dataset\graph_1.txt" , "r") as f:
    edges = []
    edge = f.readline()
    while edge:
        v1 , v2 = edge.split(",")
        v1,v2 = int(v1), int(v2)
        edges.append([v1,v2])
        edge = f.readline()
    print(edges)
    print(np.amax(edges))
adj_matrix = np.zeros([6,6])
for edge in edges:
    v1,v2 = edge
    adj_matrix[v1-1][v2-1] = 1
print(adj_matrix)
pr_matrix = adj_matrix/np.amax((edges))
print(pr_matrix)

[[1, 2], [2, 3], [3, 4], [4, 5], [5, 6]]
6
[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]
[[0.         0.16666667 0.         0.         0.         0.        ]
 [0.         0.         0.16666667 0.         0.         0.        ]
 [0.         0.         0.         0.16666667 0.         0.        ]
 [0.         0.         0.         0.         0.16666667 0.        ]
 [0.         0.         0.         0.         0.         0.16666667]
 [0.         0.         0.         0.         0.         0.        ]]


In [16]:
E_value, E_vector = np.linalg.eig(adj_matrix)
print(E_value)
print(E_vector)

[0. 0. 0. 0. 0. 0.]
